import React from "react";
import "../../App.css";
// import "../../../public/logos/l";

const Slider = () => {
  return (
    <>
      <div className="logoContainer h-[16vh] bg-dusty ">
        <div className="logo-slider h-full flex justify-between">
          <img
            src="../../../public/logos/html-5.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/js.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/py.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/node.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/python.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/mongo.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/react.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/tailwind.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/html-5.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/js.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/py.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/node.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/python.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/mongo.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/react.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/tailwind.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
        </div>
        {/* <div className="logo-slider h-full bg-slate-600 flex justify-between">
          <img
            src="../../../public/logos/html-5.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/js.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/py.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/node.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/python.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/mongo.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/react.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
          <img
            src="../../../public/logos/tailwind.svg"
            className="h-full"
            alt="HTML-LOGO"
          />
        </div> */}
      </div>
    </>
  );
};

export default Slider;
